# `brew install graphviz`
all: preprocessing hackathon

preprocessing:
	dot preprocessing.dot -Tpdf -o preprocessing.pdf && \
	open preprocessing.pdf

hackathon:
	dot hackathon.dot -Tpdf -o hackathon.pdf && \
	open hackathon.pdf
